version: "3.8"
services:
  opa:
    image: openpolicyagent/opa:latest
    ports:
      - 8181:8181
    # WARNING: OPA is NOT running with an authorization policy configured. This
    # means that clients can read and write policies in OPA. If you are
    # deploying OPA in an insecure environment, be sure to configure
    # authentication and authorization on the daemon. See the Security page for
    # details: https://www.openpolicyagent.org/docs/security.html.
    command:
      - "run"
      - "--server"
      - "--log-format=json-pretty"
      - "--set=decision_logs.console=true"
      - "--log-level=debug"
      - "api_authz.rego"
    volumes:
      - ./opa/policy/api_authz.rego:/api_authz.rego

  api_server:
    build:
      context: ./python
      dockerfile: Dockerfile.development
    environment:
      - FLASK_ENV=development
      - OPA_ADDR=http://opa:8181
      - POLICY_PATH=/v1/data/httpapi/authz
    ports:
      - 5000:5000
    volumes:
      - ./python/src:/flask
