FROM python:3.8.4-alpine3.12

ENV FLASK_APP=./server.py

RUN apk update \
&& mkdir /flask

WORKDIR /flask

COPY requirements.txt /flask/

RUN pip install -r /flask/requirements.txt

COPY src/server.py /flask/

CMD ["flask", "run", "--host=0.0.0.0"]

EXPOSE 5000
